### ISSUE TITLE
Flamelink issue

### ISSUE THREAD

**Issue by csabaxyz** [u12206050/gridsome-source-firestore#10]
Hey,

I just started using this lib. It's awesome that it exists.

However, I have an issue while using https://flamelink.io/ as the CMS.
It uses a flat collection to store the data, which is explained here:
https://intercom.help/flamelink/en/articles/3068550-flamelink-and-cloud-firestore

Now, I can define the collection through this lib, like this:
```js
ref(db) {
  return db.collection('fl_content').where('_fl_meta_.schema', '==', 'artists')
}
```
But what happens when I try to add another ref?

Because of this line both of them is going to be named the same:
https://github.com/u12206050/gridsome-source-firestore/blob/dff58d3e42529df8e9911c9ae9c24ba0ec86154a/index.js#L80

So, my suggestion would be to change that line to something like this:
```js
const cName = this.typeName(colDef.name || ref._queryOptions.collectionId, ref._queryOptions.parentPath.segments)
```

This would allow people to give a specific name to their collections, like this:
```js
collections: [{
  name: 'Artists',
  ref(db) {
    return db.collection('fl_content').where('_fl_meta_.schema', '==', 'artists')
  },
  slug(doc, slugify) {
    return `/artists/${slugify(doc.data.slug)}`
  }
}]
```
And when the `name` attribute doesn't exist, it would fall back to the previous behavior.

What do you think?
Do you have a better suggestion?

**Comment by u12206050** [comment]
Hi,

I agree that allowing a name attribute will be the best fit for allowing multiple such queries. One issue I see arising from this though would be relationships not bind correctly then, but can solve that issue once it arrises for someone.

Name attribute added in version 1.2.0

**Comment by csabaxyz** [comment]
Thanks for the fix.

> One issue I see arising from this though would be relationships not bind correctly then, but can solve that issue once it arrises for someone.

Actually we have that issue now. I didn't think of this before, but I see now why it is happenning. Any idea how that could be fixed?
