### ISSUE TITLE
Failed to run on development mode

### ISSUE THREAD

**Issue by nebnhoj** [u12206050/gridsome-source-firestore#14]
**Run on development mode**

> gridsome develop

` ERROR  Failed to compile with 1 errors                                                                                                  5:04:14 AM

 error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "title" on type "FirePosts".

GraphQL request:39:9
38 |         id
39 |         title
   |         ^
40 |         image (width: 300, height: 300)
    at Object.module.exports (/development/test/firestore-blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:28:21)

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

`

**Comment by u12206050** [comment]
That is a common graphql error in Gridsome, check your pages & templates, you are attempting to get a field called `title` but don't have `title` on your Posts? Remove it from your `page/static-query`
