### ISSUE TITLE
how to get collection ref collection data

### ISSUE THREAD

**Issue by ftpyz** [u12206050/gridsome-source-firestore#4]
hii i want to get data my ref collection data. how to get my firma field refence data please help
![Screen Shot 2019-11-17 at 18 49 01](https://user-images.githubusercontent.com/38686/69009880-f46a1e00-096a-11ea-880b-b8a9c9fa5438.png)

**Comment by Berkmann18** [comment]
Assuming you set your `gridsome.config.js` properly, say your collection is called `companies`, you'll have something like this:
```js
const { db } = require('gridsome-source-firestore')

module.exports = {
  plugins: [
    {
      use: 'gridsome-source-firestore',
      options: {
        credentials: require('./your-project-firebase-creds.json'), // Replace with your credentials file you downloaded.
        debug: true, // Default false, should be true to enable live data updates
        ignoreImages: false, // Default false
        imageDirectory: 'fg_images', // Default /fg_images
        collections: [
          {
            ref: (db) => {
              return db.collection('companies')
            },
            slug: (doc, slugify) => {
              return `/topics/${slugify(doc.data.title)}`
            }
          }
        ]
      }
    }
  ]
}
```

You would access those fields on a Vue component/view with a `static-query`/`page-query` as follows:
```vue
<page-query>
query {
  allFireTopics {
    edges {
      node {
        firma
      }
    }
  }
}
</page-query>
```

A good way to check if the query is correct is to use the GraphQLi/GraphQL Explorer interface that you can access on say http://localhost:8080/___explore (assuming your Gridsome app runs on `localhost:8080`).
You should also see the relevant firestore element being collected as their id are printed on the console.

If you want to access the fireTopics under another say: `company` you'll do something like:
```vue
<page-query>
query {
  companies: allFireTopics {
    edges {
      node {
        firma
      }
    }
  }
}
</page-query>
```
And then the data would be accessible in `$page.companies.edges` in your Vue component.

I hope it helps.
