### ISSUE TITLE
Can't Figure Out What To Do

### ISSUE THREAD

**Issue by ghost** [u12206050/gridsome-source-firestore#5]
I have a simple firestore database collection called news.  News has a number of documents with various fields:

* content
* published_date
* summary
* author
* title
* etc.

How am I supposed to set up the gridsome.config file to access this collection.  I cannot figure it out from the instructions given.

Thanks.

**Comment by u12206050** [comment]
add the following to your plugins array in `gridsome.config`
Replace with your credentials.
```
{
      use: 'gridsome-source-firestore',
      options: {
        credentials: require('./my-project-firebase-adminsdk-qw2123.json'), // Replace with your credentials file you downloaded.
        debug: true,
        ignoreImages: false,
        imageDirectory: 'fg_images',
        collections: [
          {
            ref: (db) => {
              return db.collection('news')
            },
            slug: (doc, slugify) => {
              return `/${slugify(doc.data.title)}`
            }
          }
        ]
      }
    }
```
