### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Berkmann18** [u12206050/gridsome-source-firestore#6]
When running `npm run develop` on a project that uses this package, I get this warning:
```
 WARNING  Deprecation notices

FireTopics.getNode() is deprecated. Use FireTopics.getNodeById() instead.
./node_modules/gridsome-source-firestore/index.js:149:17
```

Seems like something I could submit a PR for but I'm too busy right now.

**Comment by hacknug** [comment]
Wouldn't this only require changing this line? Are you importing this file manually from some other place?

https://github.com/u12206050/gridsome-source-firestore/blob/81f85dd63679d8d31584bc33f935d3dea45a3d3f/index.js#L149

**Comment by Berkmann18** [comment]
@hacknug Nope, I'm using `const {db} = require('gridsome-source-firestore');` as per https://github.com/u12206050/gridsome-source-firestore#usage.

**Comment by u12206050** [comment]
Fixed.
