### ISSUE TITLE
Firestore

### ISSUE THREAD

**Issue by adamsir** [u12206050/gridsome-source-firestore#7]
I know it is not so relevant to this project, but I've followed the readme and I'm stuck on this. Can you please help me out? Thanks!
`The Cloud Firestore API is not available for Cloud Datastore projects.`

**Comment by u12206050** [comment]
This project uses Firestore, make sure it is enabled in your project and that you have created a Firestore database in the console: 
![](https://user-images.githubusercontent.com/33627609/39813486-3fcfd48a-53ae-11e8-8542-f348e21bf54c.png)
