### ISSUE TITLE
Publishing to Netlify

### ISSUE THREAD

**Issue by pjmanning** [u12206050/gridsome-source-firestore#9]
Is there a way to set this up to enable it to be published to netlify?

Any current prod publish does not build because you cannot add the credientials .json file for security reasons.

Setting it up to just use env variables that could be entered in the netlify ui would be dooooope.

**Comment by u12206050** [comment]
I create the json file based on env variables on Netlify.

**Comment by pjmanning** [comment]
Ahh ok thanks!

So you do include the file with the env variables on github and create another json file that you would use locally?  Also, the private key contains line breaks so not sure how that works in the Netlify UI.

**Comment by u12206050** [comment]
NO! Never do that. I enter the variables in Netlify under build settings.

**Comment by u12206050** [comment]
In regards to the line breaks I didn't have any issue with that so it should be fine just copy and paste.

**Comment by pjmanning** [comment]
Really appreciate the help Gerard. 

I guess I don’t understand how to just add the variables in Netlify without the json file in the build as well. 

Do you simply add the json file variable names with their values in netlify... ie
project_id
private_key_id
private_key
Etc..

Then in gridsome.config.js wouldn’t you get an error on the options credentials?

**Comment by u12206050** [comment]
In gridsome.config.js you would change from:
```
{
      use: 'gridsome-source-firestore',
      options: {
        credentials: require('./firebase-adminsdk-credentials.json'),
...
```
to this:
```
{
      use: 'gridsome-source-firestore',
      options: {
        credentials: {
            "type": process.env.type,
            "project_id": process.env.project_id,
            "private_key_id": process.env.private_key_id,
            "private_key": process.env.private_key,
            "client_email": process.env.client_email,
            "client_id": process.env.client_id,
            "auth_uri": process.env.auth_uri,
            "token_uri": process.env.token_uri,
            "auth_provider_x509_cert_url": process.env.auth_provider_x509_cert_url,
            "client_x509_cert_url": process.env.client_x509_cert_url
        },
...
```

**Comment by pjmanning** [comment]
Thanks!

So I ended up with making a few minor edits...

In Netlify the private key variable was still throwing an error.  I wrapped it in quotes and then parsed the response.  

```
    {
      use: 'gridsome-source-firestore',
      options: {
        credentials: isProd
          ? {
              type: process.env.type,
              project_id: process.env.project_id,
              private_key_id: process.env.private_key_id,
              private_key: JSON.parse(process.env.private_key),
              client_email: process.env.client_email,
              client_id: process.env.client_id,
              auth_uri: process.env.auth_uri,
              token_uri: process.env.token_uri,
              auth_provider_x509_cert_url: process.env.auth_provider_x509_cert_url,
              client_x509_cert_url: process.env.client_x509_cert_url
            }
          : require('./___firebasesdkfile___.json'), 
```

Not sure if it's a best practice way to do it with dev / prod but all works great.

Really appreciate the help again @u12206050!  And thanks for all the awesome work you're doing with Gridsome and plugins.  Looking forward to using more of them!
